name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: docker make
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-test:dev && docker save -o my-test:dev.tar my-test:dev

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
          name: docker-artifact
          path: my-test:dev.tar
            
